# Generated by Django 4.2.6 on 2023-10-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='код подтверждения почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='подтвержденный через почту'),
        ),
    ]
