# Generated by Django 4.2.6 on 2023-10-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('news', 'Новости'), ('event', 'События'), ('useful material', 'Полезные материалы'), ('research', 'Исследования'), ('new test', 'Новые тесты')], default='news', max_length=15, verbose_name='Тег'),
        ),
    ]
