# Generated by Django 4.2.6 on 2023-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='Превью'),
        ),
    ]
