# Generated by Django 4.2.6 on 2023-10-22 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Создан'), ('Submitted', 'Подтвержден'), ('Paid', 'Оплачен'), ('Completed', 'Завершен')], default='Created', max_length=15, verbose_name='статус')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='сумма')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('service', models.ManyToManyField(to='main.service', verbose_name='услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
