# Generated by Django 4.2.6 on 2023-10-22 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_applicationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationForm',
            new_name='Application',
        ),
    ]
