# Generated by Django 4.2.6 on 2023-10-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_applicationform_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='microchip_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Номер чипа'),
        ),
    ]
