# Generated by Django 4.2.6 on 2023-10-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_application_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.application', verbose_name='заявка'),
        ),
    ]
