# Generated by Django 4.2.6 on 2023-10-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-create_date'], 'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create_date'], 'permissions': [('set_submit', 'Can change status')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
