# Generated by Django 4.2.6 on 2023-10-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_application_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-create_date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create_date'], 'permissions': [('set_status', 'Can change status')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
