# Generated by Django 4.2.6 on 2023-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_application_options_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='подтверждена'),
        ),
    ]
